# Audio paths
audio_dir: "./audio"
output_dir: "./data/outputs"
temp_dir: "./data/tmp"

# Audio processing (conversion controls)
audio_processing:
  convert_mp3_to_wav: true          # set false to skip conversion and feed MP3s directly to ASR
  wav_sample_rate: 16000            # -ar 16000
  wav_channels: 1                   # -ac 1 (mono)
  out_dir: "./data/tmp"             # destination for converted WAVs (matches temp_dir)
  delete_mp3_after_success: false   # set true to remove MP3s after successful conversion
  workers: null                     # null = let code choose default (e.g. cpu_count//2)
  overwrite_existing_wav: false     # set true to force reconversion even if WAV exists

# ASR settings
asr_provider: "sarvam"              # "sarvam" or "whisper" (fallback)
asr_model: "saarika:v2.5"           # Sarvam model for Tamil speech->text
asr_language_code: "ta-IN"          # Tamil language code for Sarvam
asr_batch_enabled: true             # Use batch API for longer files
asr_batch_max_files_per_job: 20     # Max files per batch job
asr_concurrency_limit: 3            # Max concurrent uploads/requests
asr_retry:
  max_attempts: 5
  backoff_factor: 2
transcript_cache_enabled: true      # Cache transcripts to avoid re-transcribing
transcript_cache_ttl_days: 30       # Cache TTL in days

# Whisper fallback settings (used when asr_provider="whisper")
whisper_model: "medium"             # Fallback Whisper model (smaller than large-v3)
language: "ta"                      # Tamil language for Whisper

# Map detected product names to product-intent tags
PRODUCT_INTENT_MAP:
  tomato: product_praise
  coriander: purchase_request
  curry_leaf: purchase_request
  coconut: purchase_positive
  gallon: purchase_request

# Field definitions
fields:
  textTamil: "Tamil text from transcription"
  textEnglish: "English translation text"
  speaker_roles: ["buyer", "seller", "customer_bystander", "other"]
  intent_categories: ["complaint", "purchase_request", "purchase_positive", "purchase_negative", "product_praise", "request_resolution", "other"]
  sentiment_labels: ["positive", "neutral", "negative"]
  emotion_categories: ["happy", "satisfied", "neutral", "annoyed", "disappointed", "frustrated"]
  new_fields:
    - role_confidence
    - products
    - action_required
    - escalation_needed
    - churn_risk
    - business_opportunity

# Sentiment analysis thresholds
sentiment_thresholds:
  positive: 0.15
  negative: -0.15
  neutral_range: [-0.15, 0.15]
  # Clear mapping: score >= 0.15 = positive, score <= -0.15 = negative, else neutral

# Placeholder values for missing metadata
placeholders:
  seller_id: "S123"
  stop_id: "STOP45"
  anchor_time: "2025-08-19T00:00:00Z"
  sales_at_stop:
    tomato: 36
    onion: 15
    potato: 10
  inventory_after_sale:
    tomato: 22
    onion: 5
    potato: 8

# NLU thresholds
confidence_threshold: 0.3
min_segment_words: 4

# Translation settings
translation:
  use_google_cloud: true  # Use Google Cloud Translate API for better quality
  fallback_to_googletrans: true
  min_words_english: 4       # Flag translations shorter than this
  low_confidence_penalty: 0.2
  fallback_to_googletrans: true  # Fallback to googletrans if Google Cloud unavailable
  batch_size: 10  # Process translations in batches
  retry_attempts: 3  # Number of retry attempts for failed translations
  
# Quality thresholds
quality_thresholds:
  min_segment_confidence: 0.5  # Minimum confidence for segments
  min_translation_quality: 0.7  # Minimum quality for translations
  max_segment_length: 200  # Maximum characters per segment
